.btn,
.window,
.window * {
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}
ul {
  list-style: none;
}
.btn{
  position:fixed;
  right: 15px;
  bottom: 30px;
  height: 30px;
  width: 80px;
  text-align: center;
  line-height: 2;
  font-size: 15px;
  background-color: #ffd300;
  color: #fff;
  border-radius: 5px;
  box-shadow: 0 0 8px #666;
  user-select: none;
  box-sizing: border-box;
}
.window{
  display:none;
  position: fixed;
  top: 0;
  left: 0;
  bottom: 0;
  right: 0;
  background-color:rgba(0, 0, 0, 0);
  .mask {
    opacity:0;
    height:100%;
    width:100%;
    z-index: 10000;
    background-color:rgba(0,0,0,.6);
    transition: opacity .3s;
  }
  .container {
    position: absolute;
    height: 70%;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 10002;
    background-color: #fff;
    transition: transform .3s;
    transform: translateY(100%);
    display: flex;
    flex-direction: column;
    .header {
      height: 40px;
      width: 100%;
      line-height: 40px;
      font-size: 14px;
      box-shadow: 0 1px 0 0 #E1E1E1;
      position: relative;
      background-color: #efeff4;
    }
    .body {
      flex: 1;
      overflow: auto;
      -webkit-overflow-scrolling: touch;
      .content {
      }
      .warn {
        color: orange;
        background-color: #fffacd;
      }
      .error {
        color: #dc143c;
        background-color: #ffe4e1;
      }
      .li {
        position: relative;
        line-height: 30px;
        height: 30px;
        overflow: hidden;
        padding-left: 5px;
        .word {
          display: block;
          margin-right: 75px;
          overflow: auto;
          .arg {
            font-size:12px;
            vertical-align: top;
            overflow : hidden;
            text-overflow: ellipsis;
            display: -webkit-box;
            -webkit-line-clamp: 1;
            -webkit-box-orient: vertical;
            overflow-x: auto;
            float: left;
            padding: 0 5px;
          }
        }
        .time {
          position: absolute;
          color: #888;
          width: 75px;
          line-height: 30px;
          text-align: center;
          font-size: 14px;
          top: 0;
          right: 0;
        }
      }
      .error:after,
      .warn:after,
      .li:after {
        content: '';
        position: absolute;
        top: -50%;
        bottom: -50%;
        left: -50%;
        right: -50%;
        -webkit-transform: scale(0.5);
        transform: scale(0.5);
        border-bottom: 1px solid #e1e1e1;
        -webkit-border-radius: 0;
        border-radius: 0;
      }
      .error:after {
        border-color:#f4a0ab;
      }
      .warn:after {
        border-color:#ffb930;
      }
      .ctOpen {
        height: auto;
        overflow: auto;
        .arg {
          -webkit-line-clamp: initial!important;
        }
      }
    }
    .footer {
      height: 50px;
      width: 100%;
      line-height: 50px;
      font-size: 14px;
      box-shadow: 0 -1px 0 0 #E1E1E1;
      position: relative;
      background-color: #efeff4;
      display: flex;
      flex-direction: row;
      .input {
        flex:1;
        font-size: 14px;
        outline:none;
        border: 0px solid #fff;
        border-radius:0;
      }
      .enter,
      .clear {
        display:inline-block;
        height:100%;
        width:60px;
        background-color:#efeff4;
        text-align: center;
        box-shadow: -1px 0px 0 0 #E1E1E1;
      }
      .clear {
      }
    }
  }
}

.show {
  display:block!important;
}
.open .mask {
  opacity:1;
}
.open .container {
  transform: translateY(0);
}